In [ ]:
import pandas as pd

data_1 = pd.read_csv("/content/Index__Violent__Property__and_Firearm_Rates_By_County__Beginning_1990(1).csv")
data_2 = pd.read_csv("/content/Index_Crimes_by_County_and_Agency__Beginning_1990_20240221.csv")

In [ ]:
data_1.head(5)

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
0,Albany,1990,292594.0,14418,4927.6,1524,520.9,12894,4406.8,122.0,41.7
1,Albany,1991,294030.0,15464,5259.3,1674,569.3,13790,4690.0,120.0,40.8
2,Albany,1992,295018.0,16249,5507.8,1588,538.3,14661,4969.5,116.0,39.3
3,Albany,1993,294302.0,15139,5144.0,1669,567.1,13470,4576.9,104.0,35.3
4,Albany,1994,293843.0,16724,5691.5,1771,602.7,14953,5088.8,162.0,55.1

In [ ]:
data_1.isnull()

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
2041,False,False,False,False,False,False,False,False,False,False,False
2042,False,False,False,False,False,False,False,False,False,False,False
2043,False,False,False,False,False,False,False,False,False,False,False
2044,False,False,False,False,False,False,False,False,False,False,False
2045,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data_1.isnull().sum()

County             0
Year               0
Population         0
Index Count        0
Index Rate         0
Violent Count      0
Violent Rate       0
Property Count     0
Property Rate      0
Firearm Count     65
Firearm Rate      65
dtype: int64

In [ ]:
data_2.head(5)

,County,Agency,Year,Months Reported,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft,Region
0,Albany,Albany City PD,2022.0,12.0,4746.0,944.0,14.0,70.0,233.0,627.0,3802.0,566.0,2670.0,566.0,Non-New York City
1,Albany,Albany County Park PD,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City
2,Albany,Albany County Sheriff,2022.0,12.0,127.0,11.0,0.0,3.0,1.0,7.0,116.0,10.0,97.0,9.0,Non-New York City
3,Albany,Albany County State Police,2022.0,12.0,131.0,42.0,0.0,26.0,5.0,11.0,89.0,7.0,77.0,5.0,Non-New York City
4,Albany,Altamont Vg PD,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City

In [ ]:
data_2.isnull()

,County,Agency,Year,Months Reported,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft,Region
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13014,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13015,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13016,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13017,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13018,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
data_2 = data_2.drop(13018)

In [ ]:
data_2.isnull().sum()

County                    0
Agency                    0
Year                      0
Months Reported        1173
Index Total               0
Violent Total             0
Murder                    0
Rape                      0
Robbery                   0
Aggravated Assault        0
Property Total            0
Burglary                  0
Larceny                   0
Motor Vehicle Theft       0
Region                    0
dtype: int64

In [ ]:
data_2.loc[data_2["County"] == "Albany"]

,County,Agency,Year,Months Reported,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft,Region
0,Albany,Albany City PD,2022.0,12.0,4746.0,944.0,14.0,70.0,233.0,627.0,3802.0,566.0,2670.0,566.0,Non-New York City
1,Albany,Albany County Park PD,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City
2,Albany,Albany County Sheriff,2022.0,12.0,127.0,11.0,0.0,3.0,1.0,7.0,116.0,10.0,97.0,9.0,Non-New York City
3,Albany,Albany County State Police,2022.0,12.0,131.0,42.0,0.0,26.0,5.0,11.0,89.0,7.0,77.0,5.0,Non-New York City
4,Albany,Altamont Vg PD,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12406,Albany,Guilderland Town PD,2003.0,12.0,1070.0,23.0,0.0,0.0,7.0,16.0,1047.0,89.0,938.0,20.0,Non-New York City
12407,Albany,Menands Vg PD,2003.0,12.0,119.0,2.0,0.0,0.0,1.0,1.0,117.0,20.0,92.0,5.0,Non-New York City
12408,Albany,Ravena Vg PD,2003.0,12.0,19.0,1.0,0.0,0.0,1.0,0.0,18.0,4.0,14.0,0.0,Non-New York City
12409,Albany,SUNY - Albany,2003.0,12.0,276.0,7.0,0.0,1.0,2.0,4.0,269.0,23.0,243.0,3.0,Non-New York City
12410,Albany,Watervliet City PD,2003.0,12.0,247.0,25.0,2.0,0.0,5.0,18.0,222.0,50.0,152.0,20.0,Non-New York City

In [ ]:
#data_2_agency_dropped = data_2.drop("Agency", axis=1)
#data_2_agency_dropped.head(5)

,County,Year,Months Reported,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft,Region
0,Albany,2022.0,12.0,4746.0,944.0,14.0,70.0,233.0,627.0,3802.0,566.0,2670.0,566.0,Non-New York City
1,Albany,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City
2,Albany,2022.0,12.0,127.0,11.0,0.0,3.0,1.0,7.0,116.0,10.0,97.0,9.0,Non-New York City
3,Albany,2022.0,12.0,131.0,42.0,0.0,26.0,5.0,11.0,89.0,7.0,77.0,5.0,Non-New York City
4,Albany,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,Non-New York City

In [ ]:
#data_2_agency_region_dropped = data_2_agency_dropped.drop("Region", axis = 1)
#data_2_agency_region_dropped.head(5)

,County,Year,Months Reported,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
0,Albany,2022.0,12.0,4746.0,944.0,14.0,70.0,233.0,627.0,3802.0,566.0,2670.0,566.0
1,Albany,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,Albany,2022.0,12.0,127.0,11.0,0.0,3.0,1.0,7.0,116.0,10.0,97.0,9.0
3,Albany,2022.0,12.0,131.0,42.0,0.0,26.0,5.0,11.0,89.0,7.0,77.0,5.0
4,Albany,2022.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [ ]:
data_2.columns

Index(['County', 'Agency', 'Year', 'Months Reported', 'Index Total',
       'Violent Total', 'Murder', 'Rape', 'Robbery', 'Aggravated Assault',
       'Property Total', 'Burglary', 'Larceny', 'Motor Vehicle Theft',
       'Region'],
      dtype='object')

In [ ]:
aggregate_fn = {'Index Total':"sum", 'Violent Total':"sum",
       'Murder':"sum", 'Rape':"sum", 'Robbery':"sum", 'Aggravated Assault':"sum", 'Property Total':"sum",
       'Burglary':"sum", 'Larceny':"sum", 'Motor Vehicle Theft':"sum"}
df_grouped = data_2.groupby(["County", "Year"], as_index = False).aggregate(aggregate_fn)
df_grouped.head(5)

,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
0,Albany,2003.0,23954.0,2804.0,22.0,102.0,872.0,1808.0,21150.0,4136.0,15766.0,1248.0
1,Albany,2004.0,25420.0,2862.0,28.0,154.0,962.0,1718.0,22558.0,3982.0,17224.0,1352.0
2,Albany,2005.0,24238.0,3230.0,26.0,192.0,1022.0,1990.0,21008.0,4088.0,15780.0,1140.0
3,Albany,2006.0,23870.0,3090.0,10.0,142.0,910.0,2028.0,20780.0,3484.0,16408.0,888.0
4,Albany,2007.0,21168.0,2936.0,10.0,150.0,874.0,1902.0,18232.0,3170.0,14208.0,854.0

In [ ]:
df_grouped.isnull().sum()

County                 0
Year                   0
Index Total            0
Violent Total          0
Murder                 0
Rape                   0
Robbery                0
Aggravated Assault     0
Property Total         0
Burglary               0
Larceny                0
Motor Vehicle Theft    0
dtype: int64

In [ ]:
data_1.head(35)

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
0,Albany,1990,292594.0,14418,4927.6,1524,520.9,12894,4406.8,122.0,41.7
1,Albany,1991,294030.0,15464,5259.3,1674,569.3,13790,4690.0,120.0,40.8
2,Albany,1992,295018.0,16249,5507.8,1588,538.3,14661,4969.5,116.0,39.3
3,Albany,1993,294302.0,15139,5144.0,1669,567.1,13470,4576.9,104.0,35.3
4,Albany,1994,293843.0,16724,5691.5,1771,602.7,14953,5088.8,162.0,55.1
5,Albany,1995,290756.0,16699,5743.3,1606,552.4,15093,5191.0,157.0,54.0
6,Albany,1996,291536.0,13676,4691.0,1408,483.0,12268,4208.1,117.0,40.1
7,Albany,1997,290760.0,14542,5001.4,1450,498.7,13092,4502.7,149.0,51.2
8,Albany,1998,294930.0,13733,4656.4,1310,444.2,12423,4212.2,108.0,36.6
9,Albany,1999,292929.0,14145,4828.8,1133,386.8,13012,4442.0,113.0,38.6
10,Albany,2000,304521.0,14096,4628.9,1353,444.3,12743,4184.6,153.0,50.2
11,Albany,2001,295107.0,13733,4653.6,1649,558.8,12084,4094.8,252.0,85.4
12,Albany,2002,297376.0,12784,4298.9,1706,573.7,11078,3725.3,224.0,75.3
13,Albany,2003,296677.0,11977,4037.1,1402,472.6,10575,3564.5,183.0,61.7
14,Albany,2004,298419.0,12710,4259.1,1431,479.5,11279,3779.6,194.0,65.0
15,Albany,2005,298859.0,12119,4055.1,1615,540.4,10504,3514.7,260.0,87.0
16,Albany,2006,298210.0,11935,4002.2,1545,518.1,10390,3484.1,200.0,67.1
17,Albany,2007,297154.0,10584,3561.8,1468,494.0,9116,3067.8,208.0,70.0
18,Albany,2008,299789.0,10750,3585.9,1356,452.3,9394,3133.5,238.0,79.4
19,Albany,2009,298400.0,10613,3556.6,1289,432.0,9324,3124.7,191.0,64.0
20,Albany,2010,295267.0,11037,3738.0,1182,400.3,9855,3337.7,154.0,52.2
21,Albany,2011,305571.0,10727,3510.5,1166,381.6,9561,3128.9,196.0,64.1
22,Albany,2012,305204.0,9974,3268.0,1011,331.3,8963,2936.7,137.0,44.9
23,Albany,2013,306300.0,9456,3087.2,1005,328.1,8451,2759.1,151.0,49.3
24,Albany,2014,308166.0,9186,2980.9,1003,325.5,8183,2655.4,147.0,47.7
25,Albany,2015,308613.0,8644,2800.9,1041,337.3,7603,2463.6,114.0,36.9
26,Albany,2016,308401.0,8766,2842.4,1099,356.4,7667,2486.0,125.0,40.5
27,Albany,2017,310352.0,8792,2832.9,1162,374.4,7630,2458.5,148.0,47.7
28,Albany,2018,304591.0,8346,2740.1,1097,360.2,7249,2379.9,157.0,51.5
29,Albany,2019,305810.0,8004,2617.3,997,326.0,7007,2291.3,138.0,45.1
30,Albany,2020,303723.0,7404,2437.7,1097,361.2,6307,2076.6,238.0,78.4
31,Albany,2021,311537.0,7861,2523.3,1131,363.0,6730,2160.3,257.0,82.5
32,Albany,2022,315477.0,9717,3080.1,1253,397.2,8464,2682.9,283.0,89.7
33,Allegany,1990,50470.0,1280,2536.2,146,289.3,1134,2246.9,1.0,2.0
34,Allegany,1991,50654.0,1417,2797.4,134,264.5,1283,2532.9,4.0,7.9

In [ ]:
df_grouped.head(25)

,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
0,Albany,2003.0,23954.0,2804.0,22.0,102.0,872.0,1808.0,21150.0,4136.0,15766.0,1248.0
1,Albany,2004.0,25420.0,2862.0,28.0,154.0,962.0,1718.0,22558.0,3982.0,17224.0,1352.0
2,Albany,2005.0,24238.0,3230.0,26.0,192.0,1022.0,1990.0,21008.0,4088.0,15780.0,1140.0
3,Albany,2006.0,23870.0,3090.0,10.0,142.0,910.0,2028.0,20780.0,3484.0,16408.0,888.0
4,Albany,2007.0,21168.0,2936.0,10.0,150.0,874.0,1902.0,18232.0,3170.0,14208.0,854.0
5,Albany,2008.0,21500.0,2712.0,20.0,146.0,908.0,1638.0,18788.0,3320.0,14806.0,662.0
6,Albany,2009.0,21226.0,2578.0,24.0,118.0,800.0,1636.0,18648.0,3042.0,14902.0,704.0
7,Albany,2010.0,22074.0,2364.0,6.0,122.0,734.0,1502.0,19710.0,3188.0,15812.0,710.0
8,Albany,2011.0,21454.0,2332.0,14.0,94.0,792.0,1432.0,19122.0,3142.0,15478.0,502.0
9,Albany,2012.0,19948.0,2022.0,12.0,134.0,624.0,1252.0,17926.0,3004.0,14400.0,522.0
10,Albany,2013.0,18912.0,2010.0,18.0,94.0,586.0,1312.0,16902.0,2406.0,13996.0,500.0
11,Albany,2014.0,18372.0,2006.0,28.0,92.0,632.0,1254.0,16366.0,2258.0,13642.0,466.0
12,Albany,2015.0,17288.0,2082.0,12.0,190.0,578.0,1302.0,15206.0,1880.0,12884.0,442.0
13,Albany,2016.0,17532.0,2198.0,10.0,214.0,586.0,1388.0,15334.0,1798.0,13104.0,432.0
14,Albany,2017.0,17584.0,2324.0,16.0,232.0,626.0,1450.0,15260.0,1576.0,13230.0,454.0
15,Albany,2018.0,16692.0,2194.0,30.0,238.0,516.0,1410.0,14498.0,1488.0,12554.0,456.0
16,Albany,2019.0,16008.0,1994.0,16.0,258.0,466.0,1254.0,14014.0,1494.0,12030.0,490.0
17,Albany,2020.0,14808.0,2194.0,34.0,216.0,428.0,1516.0,12614.0,1432.0,10324.0,858.0
18,Albany,2021.0,15722.0,2262.0,40.0,214.0,416.0,1592.0,13460.0,1338.0,11122.0,1000.0
19,Albany,2022.0,19434.0,2506.0,34.0,262.0,610.0,1600.0,16928.0,1794.0,13590.0,1544.0
20,Allegany,2003.0,1692.0,200.0,2.0,24.0,8.0,166.0,1492.0,356.0,1098.0,38.0
21,Allegany,2004.0,1886.0,194.0,0.0,38.0,4.0,152.0,1692.0,404.0,1226.0,62.0
22,Allegany,2005.0,2138.0,268.0,0.0,74.0,10.0,184.0,1870.0,468.0,1360.0,42.0
23,Allegany,2006.0,1678.0,238.0,4.0,26.0,6.0,202.0,1440.0,298.0,1110.0,32.0
24,Allegany,2007.0,1420.0,172.0,2.0,20.0,4.0,146.0,1248.0,390.0,826.0,32.0

,0,1,2,3,4,5,6,7,8,9,...,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045
Population,292594.0,294030.0,295018.0,294302.0,293843.0,290756.0,291536.0,290760.0,294930.0,292929.0,...,25375.0,25146.0,25121.0,24823.0,24910.0,24430.0,24639.0,24704.0,25366.0,24702.0
Firearm Count,122.0,120.0,116.0,104.0,162.0,157.0,117.0,149.0,108.0,113.0,...,0.0,3.0,1.0,2.0,2.0,1.0,0.0,3.0,1.0,1.0
Firearm Rate,41.7,40.8,39.3,35.3,55.1,54.0,40.1,51.2,36.6,38.6,...,0.0,11.9,4.0,8.1,8.0,4.1,0.0,12.1,3.9,4.0

In [ ]:
data_1_from_2003 = data_1.loc[data_1["Year"] >= 2003]

In [ ]:
data_1_from_2003.reset_index(drop=True, inplace = True)

In [ ]:
data_1_from_2003.tail(30)

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
1210,Wyoming,2013,41875.0,510,1217.9,41,97.9,469,1120.0,6.0,14.3
1211,Wyoming,2014,41454.0,380,916.7,36,86.8,344,829.8,3.0,7.2
1212,Wyoming,2015,40883.0,422,1032.2,58,141.9,364,890.3,5.0,12.2
1213,Wyoming,2016,40531.0,327,806.8,48,118.4,279,688.4,1.0,2.5
1214,Wyoming,2017,40666.0,346,850.8,71,174.6,275,676.2,5.0,12.3
1215,Wyoming,2018,39510.0,333,842.8,63,159.5,270,683.4,3.0,7.6
1216,Wyoming,2019,39619.0,257,648.7,46,116.1,211,532.6,1.0,2.5
1217,Wyoming,2020,39363.0,304,772.3,45,114.3,259,658.0,2.0,5.1
1218,Wyoming,2021,40232.0,262,651.2,52,129.3,210,522.0,0.0,0.0
1219,Wyoming,2022,40887.0,271,662.8,50,122.3,221,540.5,3.0,7.3
1220,Yates,2003,24565.0,360,1465.5,30,122.1,330,1343.4,0.0,0.0
1221,Yates,2004,24768.0,326,1316.2,30,121.1,296,1195.1,2.0,8.1
1222,Yates,2005,24704.0,302,1222.5,19,76.9,283,1145.6,0.0,0.0
1223,Yates,2006,24822.0,373,1502.7,23,92.7,350,1410.0,1.0,4.0
1224,Yates,2007,24679.0,337,1365.5,13,52.7,324,1312.9,0.0,0.0
1225,Yates,2008,24542.0,284,1157.2,15,61.1,269,1096.1,1.0,4.1
1226,Yates,2009,24634.0,350,1420.8,11,44.7,339,1376.1,0.0,0.0
1227,Yates,2010,24182.0,474,1960.1,18,74.4,456,1885.7,1.0,4.1
1228,Yates,2011,25462.0,410,1610.2,13,51.1,397,1559.2,0.0,0.0
1229,Yates,2012,25591.0,428,1672.5,20,78.2,408,1594.3,2.0,7.8
1230,Yates,2013,25375.0,413,1627.6,14,55.2,399,1572.4,0.0,0.0
1231,Yates,2014,25146.0,321,1276.5,18,71.6,303,1205.0,3.0,11.9
1232,Yates,2015,25121.0,299,1190.2,25,99.5,274,1090.7,1.0,4.0
1233,Yates,2016,24823.0,320,1289.1,17,68.5,303,1220.6,2.0,8.1
1234,Yates,2017,24910.0,259,1039.7,26,104.4,233,935.4,2.0,8.0
1235,Yates,2018,24430.0,245,1002.9,17,69.6,228,933.3,1.0,4.1
1236,Yates,2019,24639.0,187,759.0,23,93.3,164,665.6,0.0,0.0
1237,Yates,2020,24704.0,221,894.6,16,64.8,205,829.8,3.0,12.1
1238,Yates,2021,25366.0,183,721.4,34,134.0,149,587.4,1.0,3.9
1239,Yates,2022,24702.0,185,748.9,28,113.4,157,635.6,1.0,4.0

In [ ]:
data_1_from_2003.shape

(1240, 11)

In [ ]:
df_grouped.tail(5)

,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
1233,Yates,2018.0,490.0,34.0,2.0,8.0,0.0,24.0,456.0,104.0,342.0,10.0
1234,Yates,2019.0,374.0,46.0,0.0,24.0,0.0,22.0,328.0,84.0,240.0,4.0
1235,Yates,2020.0,442.0,32.0,2.0,16.0,2.0,12.0,410.0,48.0,358.0,4.0
1236,Yates,2021.0,366.0,68.0,0.0,42.0,0.0,26.0,298.0,28.0,256.0,14.0
1237,Yates,2022.0,370.0,56.0,0.0,38.0,2.0,16.0,314.0,56.0,240.0,18.0

In [ ]:
for i in data_1_from_2003.index:
    try:
        if (data_1_from_2003["County"][i] == df_grouped["County"][i]) and (data_1_from_2003["Year"][i] == df_grouped["Year"][i]):
            pass
        else:
            print("error", i)
    except:
        print("Exception at", i)

In [ ]:
data_1_from_2003.iloc[1190:1202]

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
1190,Westchester,2013,966498.0,14135,1462.5,2192,226.8,11943,1235.7,284.0,29.4
1191,Westchester,2014,974944.0,12106,1241.7,2149,220.4,9957,1021.3,270.0,27.7
1192,Westchester,2015,976316.0,12240,1253.7,2148,220.0,10092,1033.7,306.0,31.3
1193,Westchester,2016,975138.0,12543,1286.3,2116,217.0,10427,1069.3,330.0,33.8
1194,Westchester,2017,980819.0,11580,1180.6,1953,199.1,9627,981.5,295.0,30.1
1195,Westchester,2018,966057.0,9848,1019.4,1678,173.7,8170,845.7,203.0,21.0
1196,Westchester,2019,964433.0,9664,1002.0,1633,169.3,8031,832.7,185.0,19.2
1197,Westchester,2020,963247.0,10308,1070.1,1584,164.4,8724,905.7,230.0,23.9
1198,Westchester,2021,992573.0,9286,935.5,1521,153.2,7765,782.3,220.0,22.2
1199,Westchester,2022,1000049.0,11193,1119.2,1677,167.7,9516,951.6,243.0,24.3
1200,Wyoming,2003,43238.0,1006,2326.7,80,185.0,926,2141.6,2.0,4.6
1201,Wyoming,2004,43015.0,681,1583.2,58,134.8,623,1448.3,3.0,7.0

In [ ]:
df_grouped.iloc[1190:1205]

,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
1190,Westchester,2013.0,28270.0,4384.0,22.0,118.0,1686.0,2558.0,23886.0,3356.0,19292.0,1238.0
1191,Westchester,2014.0,24212.0,4298.0,28.0,130.0,1608.0,2532.0,19914.0,2980.0,15990.0,944.0
1192,Westchester,2015.0,24480.0,4296.0,34.0,342.0,1478.0,2442.0,20184.0,2614.0,16206.0,1364.0
1193,Westchester,2016.0,25086.0,4232.0,48.0,288.0,1536.0,2360.0,20854.0,2656.0,16980.0,1218.0
1194,Westchester,2017.0,23160.0,3906.0,38.0,270.0,1200.0,2398.0,19254.0,2020.0,16062.0,1172.0
1195,Westchester,2018.0,19696.0,3356.0,28.0,254.0,904.0,2170.0,16340.0,1644.0,13792.0,904.0
1196,Westchester,2019.0,19328.0,3266.0,26.0,236.0,900.0,2104.0,16062.0,1344.0,13782.0,936.0
1197,Westchester,2020.0,20616.0,3168.0,50.0,224.0,790.0,2104.0,17448.0,1636.0,14328.0,1484.0
1198,Westchester,2021.0,18572.0,3042.0,40.0,190.0,762.0,2050.0,15530.0,1482.0,12696.0,1352.0
1199,Westchester,2022.0,22386.0,3354.0,20.0,196.0,888.0,2250.0,19032.0,1540.0,15888.0,1604.0
1200,Wyoming,2004.0,1362.0,116.0,2.0,14.0,6.0,94.0,1246.0,220.0,980.0,46.0
1201,Wyoming,2005.0,1408.0,166.0,0.0,14.0,2.0,150.0,1242.0,228.0,962.0,52.0
1202,Wyoming,2006.0,1506.0,200.0,2.0,24.0,6.0,168.0,1306.0,314.0,936.0,56.0
1203,Wyoming,2007.0,1282.0,108.0,0.0,22.0,4.0,82.0,1174.0,246.0,888.0,40.0
1204,Wyoming,2008.0,1094.0,104.0,0.0,8.0,12.0,84.0,990.0,220.0,744.0,26.0

In [ ]:
data_1_from_2003.drop(1200,inplace=True)
data_1_from_2003.reset_index(drop=True, inplace=True)

<ipython-input-115-db4d258d40a1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1_from_2003.drop(1200,inplace=True)

In [ ]:
for i in data_1_from_2003.index:
    try:
        if (data_1_from_2003["County"][i] == df_grouped["County"][i]) and (data_1_from_2003["Year"][i] == df_grouped["Year"][i]):
            pass
        else:
            print("error", i)
    except:
        print("Exception at", i)

In [ ]:
data_1_from_2003.iloc[1217:1222]

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
1217,Wyoming,2021,40232.0,262,651.2,52,129.3,210,522.0,0.0,0.0
1218,Wyoming,2022,40887.0,271,662.8,50,122.3,221,540.5,3.0,7.3
1219,Yates,2003,24565.0,360,1465.5,30,122.1,330,1343.4,0.0,0.0
1220,Yates,2004,24768.0,326,1316.2,30,121.1,296,1195.1,2.0,8.1
1221,Yates,2005,24704.0,302,1222.5,19,76.9,283,1145.6,0.0,0.0

In [ ]:
df_grouped.iloc[1217:1222]

,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
1217,Wyoming,2021.0,524.0,104.0,0.0,50.0,4.0,50.0,420.0,82.0,318.0,20.0
1218,Wyoming,2022.0,542.0,100.0,0.0,30.0,0.0,70.0,442.0,64.0,360.0,18.0
1219,Yates,2004.0,652.0,60.0,0.0,16.0,6.0,38.0,592.0,174.0,404.0,14.0
1220,Yates,2005.0,604.0,38.0,0.0,6.0,4.0,28.0,566.0,156.0,406.0,4.0
1221,Yates,2006.0,746.0,46.0,0.0,8.0,6.0,32.0,700.0,140.0,542.0,18.0

In [ ]:
data_1_from_2003.drop(1219,inplace=True)
data_1_from_2003.reset_index(drop=True, inplace=True)

<ipython-input-122-109a0c66d519>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1_from_2003.drop(1219,inplace=True)

In [ ]:
data_1_from_2003

,County,Year,Population,Index Count,Index Rate,Violent Count,Violent Rate,Property Count,Property Rate,Firearm Count,Firearm Rate
0,Albany,2003,296677.0,11977,4037.1,1402,472.6,10575,3564.5,183.0,61.7
1,Albany,2004,298419.0,12710,4259.1,1431,479.5,11279,3779.6,194.0,65.0
2,Albany,2005,298859.0,12119,4055.1,1615,540.4,10504,3514.7,260.0,87.0
3,Albany,2006,298210.0,11935,4002.2,1545,518.1,10390,3484.1,200.0,67.1
4,Albany,2007,297154.0,10584,3561.8,1468,494.0,9116,3067.8,208.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...
1233,Yates,2018,24430.0,245,1002.9,17,69.6,228,933.3,1.0,4.1
1234,Yates,2019,24639.0,187,759.0,23,93.3,164,665.6,0.0,0.0
1235,Yates,2020,24704.0,221,894.6,16,64.8,205,829.8,3.0,12.1
1236,Yates,2021,25366.0,183,721.4,34,134.0,149,587.4,1.0,3.9
1237,Yates,2022,24702.0,185,748.9,28,113.4,157,635.6,1.0,4.0

In [ ]:
for i in data_1_from_2003.index:
    try:
        if (data_1_from_2003["County"][i] == df_grouped["County"][i]) and (data_1_from_2003["Year"][i] == df_grouped["Year"][i]):
            pass
        else:
            print("error", i)
    except:
        print("Exception at", i)

In [ ]:
df = data_1_from_2003[["Population", "Firearm Count", "Firearm Rate"]]

In [ ]:
df.head(5)

   Population  Firearm Count  Firearm Rate
0    296677.0          183.0          61.7
1    298419.0          194.0          65.0
2    298859.0          260.0          87.0
3    298210.0          200.0          67.1
4    297154.0          208.0          70.0

In [ ]:
print(df.shape, df_grouped.shape)

(1238, 3) (1238, 12)

In [ ]:
new_df = pd.concat([df,df_grouped], axis=1)

In [ ]:
new_df

,Population,Firearm Count,Firearm Rate,County,Year,Index Total,Violent Total,Murder,Rape,Robbery,Aggravated Assault,Property Total,Burglary,Larceny,Motor Vehicle Theft
0,296677.0,183.0,61.7,Albany,2003.0,23954.0,2804.0,22.0,102.0,872.0,1808.0,21150.0,4136.0,15766.0,1248.0
1,298419.0,194.0,65.0,Albany,2004.0,25420.0,2862.0,28.0,154.0,962.0,1718.0,22558.0,3982.0,17224.0,1352.0
2,298859.0,260.0,87.0,Albany,2005.0,24238.0,3230.0,26.0,192.0,1022.0,1990.0,21008.0,4088.0,15780.0,1140.0
3,298210.0,200.0,67.1,Albany,2006.0,23870.0,3090.0,10.0,142.0,910.0,2028.0,20780.0,3484.0,16408.0,888.0
4,297154.0,208.0,70.0,Albany,2007.0,21168.0,2936.0,10.0,150.0,874.0,1902.0,18232.0,3170.0,14208.0,854.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233,24430.0,1.0,4.1,Yates,2018.0,490.0,34.0,2.0,8.0,0.0,24.0,456.0,104.0,342.0,10.0
1234,24639.0,0.0,0.0,Yates,2019.0,374.0,46.0,0.0,24.0,0.0,22.0,328.0,84.0,240.0,4.0
1235,24704.0,3.0,12.1,Yates,2020.0,442.0,32.0,2.0,16.0,2.0,12.0,410.0,48.0,358.0,4.0
1236,25366.0,1.0,3.9,Yates,2021.0,366.0,68.0,0.0,42.0,0.0,26.0,298.0,28.0,256.0,14.0
1237,24702.0,1.0,4.0,Yates,2022.0,370.0,56.0,0.0,38.0,2.0,16.0,314.0,56.0,240.0,18.0

In [ ]:
new_df.to_csv("Merged_data.csv")